foreground #c5d8dc
background #0b1826
cursor #9cce6a
selection_foreground #0b1826
selection_background #9cce6a
active_border_color #9cce6a
color0 #142b3e
color1 #df8074
color2 #9cce6a
color3 #d9bd7c
color4 #7baacb
color5 #ad9cc7
color6 #75bdbb
color7 #829da9
color8 #486474
color9 #f29a88
color10 #b9e78a
color11 #ead299
color12 #9ec8e5
color13 #c6b7de
color14 #99d9cf
color15 #edf4ef
